name: Windows Build (x86_64 & x86)

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - .github/workflows/FreeBSD.yml
      - .github/workflows/Linux.yml
  pull_request:
    types: [edited, opened, synchronize]
    paths-ignore:
      - .github/workflows/FreeBSD.yml
      - .github/workflows/Linux.yml
  workflow_dispatch:
concurrency:
  # Cancel concurrent workflows for the same PR or commit hash.
  group: ${{github.workflow}}-${{github.event_name == 'pull_request' && github.head_ref || github.sha}}
  cancel-in-progress: true

jobs:
  build:
    name: Windows (${{ matrix.arch }})
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, x86]
        include:
          - arch: x86_64
            dll_name: gamex86_64.dll
          - arch: x86
            dll_name: gamex86.dll

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Restore CMake cache
        uses: actions/cache@v4
        with:
          path: |
            build/.cmake
            build/CMakeFiles
          key: ${{ runner.os }}-cmake-${{ matrix.arch }}-${{ hashFiles('neo/CMakeLists.txt') }}
          restore-keys: ${{ runner.os }}-cmake-${{ matrix.arch }}-

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Build the engine (x86_64)
        if: matrix.arch == 'x86_64'
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17" -A x64 -DDEDICATED=ON ../neo/
          cmake --build . --config Release

      - name: Build the engine (x86)
        if: matrix.arch == 'x86'
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17" -A Win32 -DDEDICATED=ON ../neo/
          cmake --build . --config Release

      - name: Copy base files and create gamepack
        shell: pwsh
        run: |
          ./scripts/package_pk4.ps1 -PkgName "game00.pk4" -DllName "${{ matrix.dll_name }}" -OsName windows

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prey2006-windows-${{ matrix.arch }}
          path: output/windows/
          compression-level: 6
