name: Windows x86 Build
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - .github/workflows/FreeBSD.yml
      - .github/workflows/Linux.yml
  pull_request:
    types:
      - edited
      - opened
      - synchronize
    paths-ignore:
      - .github/workflows/FreeBSD.yml
      - .github/workflows/Linux.yml
  workflow_dispatch:
concurrency:
  # Cancel concurrent workflows for the same PR or commit hash.
  group: ${{github.workflow}}-${{github.event_name == 'pull_request' && github.head_ref || github.sha}}
  cancel-in-progress: true

jobs:
  job:
    name: Windows (x86) Github Auto-Builds
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get latest CMake if possible
        uses: lukka/get-cmake@latest

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "${{github.workspace}}/vcpkg"
          runVcpkgInstall: true
          vcpkgJsonGlob: "**/neo/vcpkg.json"

      - name: Run CMake+vcpkg+Ninja to build the engine.
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: "${{github.workspace}}/neo/CMakeLists.txt"
          configurePreset: "ninja-multi-vcpkg-x86"
          buildPreset: "ninja-vcpkg-release-x86"

      - name: Create binary.conf
        shell: pwsh
        run: |
          cd ${{github.workspace}}\base
          Out-Null
          @'
          // add flags for supported operating systems in this pak
          // one id per line
          // name the file binary.conf and place it in the game pak
          // 0 win-x86
          // 1 mac-ppc
          // 2 linux-x86
          0

          '@ | Out-File -FilePath ${{github.workspace}}\base\binary.conf -Encoding utf8

      - name: Package into game00.pk4
        shell: pwsh
        run: |
          $files = @(
            "binary.conf",
            "gamex86_64.dll"
          )

          if (Test-Path -Path game00.pk4) { Remove-Item -Path game00.pk4 -Force }
          Compress-Archive -Path $files -DestinationPath game00.pk4 -Force

      - name: Copy base files to the output folder
        shell: pwsh
        run: |
          cd ${{github.workspace}}
          Copy-Item -Path "base" -Destination "output/windows/base" -Recurse
          Copy-Item -Path ".github/Changelog.md" -Destination "output/windows"
          Copy-Item -Path ".github/Configuration.md" -Destination "output/windows"
          Copy-Item -Path ".github/README.md" -Destination "output/windows"

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prey2006-windows-x86_64
          path: output/windows/
